---
swagger: '2.0'
info:
  title: API V1
  version: v1
paths:
  "/schools":
    post:
      summary: Creates a school
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: school
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
          required:
          - name
      responses:
        '200':
          description: School Created
        '422':
          description: Unprocessable Entity
  "/schools/{id}":
    put:
      summary: Updates a school
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        required: true
      - name: school
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
          required:
          - name
      responses:
        '200':
          description: School Updated
        '422':
          description: Unprocessable Entity
        '404':
          description: Not Found
    delete:
      summary: Deletes a School
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        required: true
      responses:
        '200':
          description: School Deleted
        '404':
          description: Not Found
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
