---
swagger: '2.0'
info:
  title: API V1
  version: v1
paths:
  "/schools/{school_id}/orders":
    get:
      summary: Get all orders for a school
      produces:
      - application/json
      parameters:
      - name: school_id
        in: path
        required: true
      responses:
        '200':
          description: Returns all orders for a school
        '404':
          description: Not Found
    post:
      summary: Creates an order
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: school_id
        in: path
        required: true
      - name: order
        in: body
        schema:
          type: object
          properties:
            send_email:
              type: boolean
            recipients:
              type: array
              items: integer
            gifts:
              type: array
              items: string
          required:
          - recipients gifts
      responses:
        '200':
          description: Creates an Order
        '422':
          description: Unprocessable Entity
  "/schools/{school_id}/orders/{order_id}":
    put:
      summary: Updates an Order
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: school_id
        in: path
        required: true
      - name: order_id
        in: path
        required: true
      - name: order
        in: body
        schema:
          type: object
          properties:
            send_email:
              type: boolean
            recipients:
              type: array
              items: integer
            gifts:
              type: array
              items: string
          required:
          - recipients gifts
      responses:
        '200':
          description: Updates an Order
        '422':
          description: Unprocessable Entity
        '404':
          description: Not Found
  "/schools/{school_id}/orders/{order_id}/ship":
    post:
      summary: Ships an Order
      produces:
      - application/json
      parameters:
      - name: school_id
        in: path
        required: true
      - name: order_id
        in: path
        required: true
      responses:
        '200':
          description: Ships an Order
        '404':
          description: Not Found
  "/schools/{school_id}/orders/{order_id}/cancel":
    post:
      summary: Cancels an Order
      produces:
      - application/json
      parameters:
      - name: school_id
        in: path
        required: true
      - name: order_id
        in: path
        required: true
      responses:
        '200':
          description: Cancels an Order
        '404':
          description: Not Found
  "/schools/{school_id}/recipients":
    get:
      summary: Get all recipients for school
      produces:
      - application/json
      parameters:
      - name: school_id
        in: path
        required: true
      responses:
        '200':
          description: Returns all recipients for school
        '404':
          description: Not Found
    post:
      summary: Creates a recipient
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: school_id
        in: path
        required: true
      - name: recipient
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
            email:
              type: string
            address:
              type: string
          required:
          - name email address
      responses:
        '200':
          description: Recipients Created
        '422':
          description: Unprocessable Entity
  "/schools/{school_id}/recipients/{recipient_id}":
    put:
      summary: Updates a recipient
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: school_id
        in: path
        required: true
      - name: recipient_id
        in: path
        required: true
      - name: recipient
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
            email:
              type: string
            address:
              type: string
          required:
          - name email address
      responses:
        '200':
          description: Recipient Updated
        '422':
          description: Unprocessable Entity
        '404':
          description: Not Found
    delete:
      summary: Deletes a recipient
      produces:
      - application/json
      parameters:
      - name: school_id
        in: path
        required: true
      - name: recipient_id
        in: path
        required: true
      responses:
        '200':
          description: Recipient Deleted
        '404':
          description: Not Found
  "/schools":
    post:
      summary: Creates a school
      tags:
      - schools
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: school
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
          required:
          - name
      responses:
        '200':
          description: School Created
        '422':
          description: Unprocessable Entity
  "/schools/{id}":
    put:
      summary: Updates a school
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        required: true
      - name: school
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
          required:
          - name
      responses:
        '200':
          description: School Updated
        '422':
          description: Unprocessable Entity
        '404':
          description: Not Found
    delete:
      summary: Deletes a School
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        required: true
      responses:
        '200':
          description: School Deleted
        '404':
          description: Not Found
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: "/apptegy"
